### PR TITLE
Mint-Y - Improve Cinnamon calendar menu's response to text scaling changes

### LINKED ISSUE #230: In Mint-Y-Dark theme calendar not scaling to text scaling factor
Mint-Y-Dark Theme & Text Scaling Factor of 1.2 or higher covers up calendar week day names

See picture:

image

Weekday names are `...`

Note: This isn't an issue in the Linux Mint Desktop Theme.  It scales appropriately.

### PR DESCRIPTION
**Pull request by smurphos**
Closes #230

Also improves alignment of optional week numbers with the date rows.

Before
screenshot-screen-2019-09-13-060526
screenshot-screen-2019-09-13-060537
screenshot-screen-2019-09-13-060550
screenshot-screen-2019-09-13-060601
screenshot-screen-2019-09-13-060617

After
screenshot-screen-2019-09-14-182115
screenshot-screen-2019-09-14-182128
screenshot-screen-2019-09-14-182141
screenshot-screen-2019-09-14-182155
screenshot-screen-2019-09-14-182213

### CODE REVIEW

**Comment by JosephMcc** [comment]
@smurphos I tested this and it looks good. I'd be happy to merge it but can you add the other files this ends up modifying in the git tree.
src/Mint-Y/cinnamon/cinnamon-dark.css
src/Mint-Y/cinnamon/cinnamon.css

Otherwise they will show up as part of another merge down the road. If you can add those and squash it I'll merge it. Thanks.

**Comment by smurphos** [comment]
Mmm, done but it looks like it's partially reverted this commit https://github.com/linuxmint/mint-themes/commit/d427416e08dee48bf03a8cd23675d57699bc2f01 which was to the css only and wasn't applied to the scss

@collinss

**Comment by smurphos** [comment]
OK, I've applied @collinss commit from https://github.com/linuxmint/mint-themes/commit/d427416e08dee48bf03a8cd23675d57699bc2f01 to the scss and rebuilt the css again.

All good now.

**Comment by JosephMcc** [comment]
Nice. Good catch

**Pull request merged**
