### PR TITLE
Building Mint-Y-Colors gtk theme is now 100% automated

### PR DESCRIPTION
**Pull request by SebastJava**
I finally made it. That’s a lot of work.

Building Mint-Y-Colors gtk theme is now 100% automated. You no longer need to do any manual edits anymore. It takes just a few minutes to generate all the colour variations, and everything is included.

I have read and re-read all the scripts, shell and python. And i carefully followed or tweaked the already existing methods to complete the automated processes. So there is no non-sense in the programming. And it also comes with my professional image editing.

So, when you find some time, please take some time to look at this. It will save you a lot of time in the end. And you will be able to change your mind about colours over and over again... Quickly and easily.

P.S.-1: Please start by reading the README file: there is compatibility info about Inkscape there. The render-assets files are updated for the new Inkscape, but it takes 30 seconds to revert this.

P.S.-2: Compare is currently very hard to do, because there are thousands of changed files. Please take a look at my other pull request about `.gitignore` to solve this.

### CODE REVIEW

**Comment by SebastJava** [comment]
I guess this looks very heavy for reviewing. I could split it into 4-5 parts. I could describe it. Etc. Just ask.

**Comment by SebastJava** [comment]
Reminder: **colorize.py** does not do things the right way. It is not about just changing hues. Sorry. There is saturation and lightness also. My things here works the right way, imo.

**Comment by SebastJava** [comment]
When divided into 4 parts, everything becomes more understandable:

* **gtk-2.0/menubar-toolbar/** was originally automated, with the Arc theme. I just put it back as it was.
* **xfwm4/** was originally fully automated, with the Arc theme. But the images have been changed slightly since then. Being in doubt, I therefore resumed the original automation, but only on the 3 colored assets.
* **gtk-3.0/thumbnail:** I automated the creation of these thumbnails in a very simple way: a small addition to assets.svg and a small addition to render-assets.sh
* **cinnamon/thumbnail:** I automated the creation of these thumbnails with a kind of ingenious photomontage and a new script similar to the other scripts. You have to see my additions to the src/Mint-Y/cinnamon/ folder to understand.

**Review by vladut123 — APPROVED** [review]

**Comment by SebastJava** [comment]
This PR could be closed. I am into the final steps of creating FIVE little PR to replace this big one. It is approximately the same thing, but those 5 new PRs should be much easier to compare, review, and test. Things will be divided in sections...

**Comment by SebastJava** [comment]
@vladut123 Did you really review and approve all this #280?
Otherwise, i want to delete this #280 because i replaced it with my 5 new PRs:
**Creating Mint-Y-COLOR variations is now 100% automated.**

**Comment by SebastJava** [comment]
This big pull request is now divided into 5 new small pull requests: numbers 307 to 311.

**Pull request closed without merging**
