### PR TITLE
Fill icons fixed (it was 17x18 size, now 16x16 as it should be)

### LINKED ISSUE #84: Libreoffice fill icon doesn't represent color on LO 5.0
Moving here. Didn't know that LO icons is this repo.
More: https://github.com/linuxmint/mint-x-icons/issues/131

### PR DESCRIPTION
**Pull request by Yanpas**
This fixes #84 
Files changed (trimmed from wrong 17x18 to 16x16):
```
/cmd/sc_formatarea.png
/cmd/sc_fillstyle.png
```
PS maybe there are other sc_icons which has non-standart size, maybe I will run script with imagemagick to find them and notify you

### CODE REVIEW

**Comment by Yanpas** [comment]
My zip has increased from 2.1MB to 2.3MB, bit in fact there were changed only a few bytes. I use system command `zip`

**Comment by clefebvre** [comment]
Hi Yanpas,

Can you explain how to reproduce the issue? I looked at the issue and the screenshot but I can't figure what is wrong.

**Comment by Yanpas** [comment]
@clefebvre Before this commit "Fill icon" of small set of icons did not represent color, it showed small orange stripe for all colors.
sss

**Comment by clefebvre** [comment]
Thanks

**Pull request merged**
