### PR TITLE
[WIP] New colors

### PR DESCRIPTION
**Pull request by clefebvre**
This is a PR to work on the new colors.

A comment per color, trying different tints..

### CODE REVIEW

**Comment by clefebvre** [comment]
Red

**Comment by clefebvre** [comment]
Sand

**Comment by clefebvre** [comment]
Teal

**Comment by clefebvre** [comment]
Orange

**Comment by clefebvre** [comment]
Purple

**Comment by clefebvre** [comment]
Aqua

**Comment by clefebvre** [comment]
Blue

**Comment by clefebvre** [comment]
Brown

**Comment by clefebvre** [comment]
Grey

**Comment by SebastJava** [comment]
Blue:
y_hex_colors1["Blue"] = "#326FE8"
y_hex_colors2["Blue"] = "#34569C" # (#215D9C Adwaita || #34569C Mint-Y)
y_hex_colors3["Blue"] = "#769FF0"
y_hex_colors4["Blue"] = "#214A9B"

**Comment by SebastJava** [comment]
Your "Fifth try" Blue may be just perfect. I have been using it for a few days. Mostly in the light theme. I should try a dark theme version.

**Comment by SebastJava** [comment]
RED: I like the #D8283A. At first glance. I should test it. Your screenshot looks good, and when i look at the HSL numbers, well, i call it "UX standard."

**Pull request closed without merging**
