### PR TITLE
Chrome r-click menu unclickable items gray

### PR DESCRIPTION
**Pull request by Yanpas**
This fixes issue #92 . I was using this patch for an hour (ran different apps (Qt, GTK+ etc.)), and didn't face any regressions

### CODE REVIEW

**Comment by JosephMcc** [comment]
This is how mine looks: http://imgur.com/a/K1Lo5
Not sure what's wrong with it.

**Comment by Yanpas** [comment]
How does your `usr/share/themes/Mint-X*/gtk-2.0/styles/menus.rc` looks like? Like before the commit? If yes - then I'm confused, cause this commit fixed mine issue. Maybe someone has already fixed it and I have outdated version (mine version is which shipped with 17.2)

PS your menu's gray color looks better, it's identical to gtk apps.

**Comment by JosephMcc** [comment]
I apologize. You're correct. I forgot I was using a modified version of the theme. I think your fix is the proper one.

**Comment by Yanpas** [comment]
I've just reinstalled mint-themes and mint-themes-gtk3 packages and can reproduce issue. Mine browser is google-chrome-stable version 46.0.2490.80 (64-bit)

ooops, too late. Your fix is better, IMHO,  your gray color matches better to theme. Have  you created new color variable?

**Comment by Yanpas** [comment]
That's how Greybird has fixed this issue, I guess I will  open new PR
https://github.com/shimmerproject/Greybird/commit/1ddd5acb3a86f487a525c8fdaad5fdbea4618261

**Pull request closed without merging**
